### ISSUE TITLE
pls upgrade koa-csrf@3.x

### ISSUE THREAD

**Issue by xunkutech** [embbnux/kails#28]
According to [https://github.com/koajs/csrf/blob/3.0.4/README.md](url)

> For koa@>=2.x (next):

```bash
npm install --save koa-csrf@3.x
```

> For koa@<2.x:

```bash
npm install --save koa-csrf@2.x
```

**Comment by embbnux** [comment]
thanks for your notice, I will fix it tonight.
It will be welcome if you can create a pull request to fix this.

**Comment by embbnux** [comment]
#30 has fix this
