### ISSUE TITLE
npm start , i have an error.

### ISSUE THREAD

**Issue by leeeco610** [embbnux/kails#34]
E:\demos\kails>npm start

> kails@0.1.0 start E:\demos\kails
> nodemon app/index.js & webpack --config config/webpack/development.js --progress --colors --watch

[nodemon] 1.11.0
[nodemon] reading config E:\demos\kails\nodemon.json
[nodemon] to restart at any time, enter `rs`
[nodemon] ignoring: E:\demos\kails\.git/**/* .nyc_output .sass-cache bower_components coverage E:\demos\kails\node_modules/**/* E:\demos\kails\app\assets/**/* public/assets/**/*
[nodemon] watching: *.*
[nodemon] watching extensions: js,json
[nodemon] starting `babel-node app/index.js`
[nodemon] child pid: 6808
[nodemon] watching 61 files
E:\demos\kails\node_modules\.1.2.1@bindings\bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → E:\demos\kails\node_modules\.0.8.7@bcrypt\build\bcrypt_lib.node
 → E:\demos\kails\node_modules\.0.8.7@bcrypt\build\Debug\bcrypt_lib.node
 → E:\demos\kails\node_modules\.0.8.7@bcrypt\build\Release\bcrypt_lib.node
 → E:\demos\kails\node_modules\.0.8.7@bcrypt\out\Debug\bcrypt_lib.node
 → E:\demos\kails\node_modules\.0.8.7@bcrypt\Debug\bcrypt_lib.node
 → E:\demos\kails\node_modules\.0.8.7@bcrypt\out\Release\bcrypt_lib.node
 → E:\demos\kails\node_modules\.0.8.7@bcrypt\Release\bcrypt_lib.node
 → E:\demos\kails\node_modules\.0.8.7@bcrypt\build\default\bcrypt_lib.node
 → E:\demos\kails\node_modules\.0.8.7@bcrypt\compiled\6.9.5\win32\x64\bcrypt_lib.node
    at bindings (E:\demos\kails\node_modules\.1.2.1@bindings\bindings.js:88:9)
    at Object.<anonymous> (E:\demos\kails\node_modules\.0.8.7@bcrypt\bcrypt.js:3:35)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (E:\demos\kails\node_modules\.6.24.0@babel-register\lib\node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:/demos/kails/app/models/user.js:1:1)
    at Module._compile (module.js:570:32)
    at loader (E:\demos\kails\node_modules\.6.24.0@babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (E:\demos\kails\node_modules\.6.24.0@babel-register\lib\node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by embbnux** [comment]
maybe, you should reinstall bcrypt:
```
  npm uninstall bcrypt
  npm install bcrypt
```

**Comment by leeeco610** [comment]
E:\demos\kails>npm un bcrypt
- bcrypt@0.8.7 node_modules\bcrypt

E:\demos\kails>npm i bcrypt

> bcrypt@0.8.7 install E:\demos\kails\node_modules\bcrypt
> node-gyp rebuild


E:\demos\kails\node_modules\bcrypt>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\demos\kails\node_modules\bcrypt
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "bcrypt"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\demos\kails\npm-debug.log

**Comment by leeeco610** [comment]
When  i installed Python 2.7.13.  I had an other error:
It wants me to install .NET Framework2.0 SDK  and microsoft visual studio 2005.

**Comment by leeeco610** [comment]
I installed all of them, and config : 
npm config set msvs_version 2015
npm config set python python2.7。
It is not ok , too.

I try it in centos7, but it not run up.

**Comment by leeeco610** [comment]
**centos 7 errors like that:**

[root@iZ9428j1umdZ kails]# npm run db:migrate

> kails@0.1.0 db:migrate /home/lihaipeng/www/kails
> sequelize db:migrate


Sequelize [Node: 4.4.7, CLI: 2.6.0, ORM: 3.30.2]

Loaded configuration file "config/database.js".
Using environment "development".
No migrations were executed, database schema was already up to date.
[root@iZ9428j1umdZ kails]# npm run start

> kails@0.1.0 start /home/lihaipeng/www/kails
> nodemon app/index.js & webpack --config config/webpack/development.js --progress --colors --watch

[nodemon] 1.11.0
[nodemon] reading config /home/lihaipeng/www/kails/nodemon.json
[nodemon] to restart at any time, enter `rs`
[nodemon] ignoring: /home/lihaipeng/www/kails/.git/**/* .nyc_output .sass-cache bower_components coverage /home/lihaipeng/www/kails/node_modules/**/* /home/lihaipeng/www/kails/app/assets/**/* public/assets/**/*
[nodemon] watching: *.*
[nodemon] watching extensions: js,json
[nodemon] starting `babel-node app/index.js`
[nodemon] child pid: 20759
[nodemon] watching 61 files
/home/lihaipeng/www/kails/node_modules/.npminstall/koa/2.2.0/koa/lib/response.js:47
    const { res } = this;
          ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/lihaipeng/www/kails/node_modules/.npminstall/babel-register/6.24.0/babel-register/lib/node.js:152:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/lihaipeng/www/kails/node_modules/.npminstall/koa/2.2.0/koa/lib/application.js:11:18)
    at Module._compile (module.js:409:26)
[nodemon] app crashed - waiting for file changes before starting...                                                                                                              69% 326/327 build modules
app/assets/stylesheets/base.css
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]
⚠  'declaration-block-no-ignored-properties' has been deprecated and in 8.0 will be removed. [stylelint]
⚠  'comment-empty-line-before's' "between-comments" option has been deprecated and in 8.0 will be removed. Instead use the "after-comment" option. [stylelint]
⚠  'rule-non-nested-empty-line-before' has been deprecated and in 8.0 will be removed. Instead use 'rule-empty-line-before'. [stylelint]
⚠  'rule-nested-empty-line-before' has been deprecated and in 8.0 will be removed. Instead use 'rule-empty-line-before'. [stylelint]
⚠  'root-no-standard-properties' has been deprecated and in 8.0 will be removed. [stylelint]
⚠  'media-feature-no-missing-punctuation' has been deprecated and in 8.0 will be removed. [stylelint]
                                                                                                                                                            Hash: 36b29faadf27cb66d0cd
Version: webpack 1.14.0
Time: 11695ms

**Comment by leeeco610** [comment]
In centos 7 , i upgrade node version to 7.7.4,  
the following error:

[nodemon] starting `babel-node app/index.js`
[nodemon] child pid: 21189
[nodemon] watching 61 files                                                                                                                                                          10% 0/3 build modulesmodule.js:598
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The module '/home/lihaipeng/www/kails/node_modules/.npminstall/bcrypt/1.0.2/bcrypt/lib/binding/bcrypt_lib.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 46. This version of Node.js requires
NODE_MODULE_VERSION 51. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/lihaipeng/www/kails/node_modules/.npminstall/bcrypt/1.0.2/bcrypt/bcrypt.js:6:16)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/lihaipeng/www/kails/node_modules/.npminstall/babel-register/6.24.0/babel-register/lib/node.js:152:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/lihaipeng/www/kails/app/models/user.js:1:1)
[nodemon] app crashed - waiting for file changes before starting...                                                                                                              69% 326/327 build modules
app/assets/stylesheets/base.css
undefined [undefined]
undefined [undefined]
undefined [undefined]
undefined [undefined]

**Comment by embbnux** [comment]
please reinstall bcrypt after upgrade node
It's build dependent on your env

**Comment by leeeco610** [comment]
Thank you!
In centos 7 ,  now is ok !

Win 7 is not ok, maybe some package is not support.

**Comment by embbnux** [comment]
congratulation!
