### ISSUE TITLE
Upgrade Sequelize  to V4

### ISSUE THREAD

**Issue by geniuszty** [embbnux/kails#36]
Sequelize V4 is a major release and it introduces new features and breaking changes. Majority of sequelize codebase has been refactored to use ES2015 features. The following guide lists some of the changes to upgrade from v3 to v4. See the Changelog for full list of changes.

[](http://docs.sequelizejs.com/manual/tutorial/upgrade-to-v4.html)

**Comment by geniuszty** [comment]
顶

**Comment by embbnux** [comment]
Yeah, I will update it. BTW, PR is welcome. Thanks.

**Comment by embbnux** [comment]
updated
